name: Test Project
on:
  push:
    paths:
      - '.github/workflows/test.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code Checkout
        uses: actions/checkout@v5
      - name:  Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Run test
        run: echo "For testing purpose"
        
          